name: Build NPM Lib

on:
  workflow_call:
  workflow_dispatch:

env:
  APP_NAME: piccy
  APP_PATH: piccy_node

jobs:
  build_windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64

    steps:
      - name: 检出仓库
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 设置 rust
        uses: puniyu/setup-rust@124df6330fd025f51272c7a4961a0071a3fa3e8b # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 设置 Nodejs
        uses: puniyu/setup-node@487ded571972c36333a74ed703796cec3e6cca09 # main
        with:
          node-version: lts/*
          pnpm-version: 10.25.0
          cache: true

      - name: 构建
        run: |
          pnpm install
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: ${{ env.APP_PATH }}

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            ${{ env.APP_PATH }}/dist/${{ env.APP_NAME }}*.node

  build_macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-latest
            target: x86_64-apple-darwin
            label: macos-x86_64
          - runner: macos-latest
            target: aarch64-apple-darwin
            label: macos-aarch64

    steps:
      - name: 检出仓库
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 设置 rust
        uses: puniyu/setup-rust@124df6330fd025f51272c7a4961a0071a3fa3e8b # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 设置 Nodejs
        uses: puniyu/setup-node@487ded571972c36333a74ed703796cec3e6cca09 # main
        with:
          node-version: lts/*
          pnpm-version: 10.25.0
          cache: true

      - name: 构建
        run: |
          pnpm install
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: ${{ env.APP_PATH }}

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            ${{ env.APP_PATH }}/dist/${{ env.APP_NAME }}*.node

  build_linux:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            label: linux-x86_64
            container: ghcr.io/puniyu/debian:latest
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            label: linux-aarch64
            container: ghcr.io/puniyu/debian:latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 设置 rust
        uses: puniyu/setup-rust@124df6330fd025f51272c7a4961a0071a3fa3e8b # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 设置 Nodejs
        uses: puniyu/setup-node@487ded571972c36333a74ed703796cec3e6cca09 # main
        with:
          node-version: lts/*
          pnpm-version: 10.25.0
          cache: true

      - name: 构建
        run: |
          pnpm install
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: ${{ env.APP_PATH }}

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            ${{ env.APP_PATH }}/dist/${{ env.APP_NAME }}*.node
  
  build_wasm:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: wasm32-wasip1-threads
            label: wasm32-wasi

    steps:
      - name: 检出仓库
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 设置 rust
        uses: puniyu/setup-rust@124df6330fd025f51272c7a4961a0071a3fa3e8b # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 设置 Nodejs
        uses: puniyu/setup-node@487ded571972c36333a74ed703796cec3e6cca09 # main
        with:
          node-version: lts/*
          pnpm-version: 10.25.0
          cache: true

      - name: 构建
        run: |
          pnpm install
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: ${{ env.APP_PATH }}

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            ${{ env.APP_PATH }}/dist/${{ env.APP_NAME }}*.wasm


      - name: 上传npm包
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "npm-package"
          path: |
            ${{ env.APP_PATH }}/dist/index.js
            ${{ env.APP_PATH }}/dist/index.d.ts
            ${{ env.APP_PATH }}/package.json      

      - name: 上传wasm包
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "npm-wasm"
          path: |
            ${{ env.APP_PATH }}/dist/piccy.wasi.cjs
            ${{ env.APP_PATH }}/dist/piccy.wasi-browser.js
            ${{ env.APP_PATH }}/dist/wasi-worker.mjs
            ${{ env.APP_PATH }}/dist/wasi-worker-browser.mjs