name: Build Tauri App

on:
  workflow_call:
    secrets:
      STORE_PASSWORD:
        required: true
      KEY_ALIAS:
        required: true
      KEY_PASSWORD:
        required: true
      BASE64_JKS:
        required: true

env:
  APP_NAME: piccy

jobs:
  build_windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64

    steps:
      - name: 检出仓库
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 设置 rust
        uses: puniyu/setup-rust@a6d1a3adea77d13cf52ef1c0d9c02dc11f620e5a # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}
          tools: tauri-cli

      - name: Setup Nodejs
        uses: puniyu/setup-node@bc6a83c5c09bd93e10596d6a9938fcfe5841f434 # main
        with:
          node-version: lts/*
          pnpm-version: 10.25.0
          cache: true

      - name: 构建
        run: |
          pnpm install
          cargo tauri build --target ${{ matrix.platform.target }}
        working-directory: piccy_app

      - name: 上传构建产物
        id: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-app-${{ matrix.platform.label }}"
          path: |
            target/${{ matrix.platform.target }}/release/bundle/nsis/${{ env.APP_NAME }}*.exe

      - name: 生成构建信息
        shell: bash
        run: |
          VERSION=$(jq -r '.version' piccy_app/tauri.conf.json)
          NAME=$(jq -r '.productName' piccy_app/tauri.conf.json)
          
          echo "## Windows桌面应用构建完成" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 应用信息" >> $GITHUB_STEP_SUMMARY
          echo "- **应用名称:** `${NAME}`" >> $GITHUB_STEP_SUMMARY
          echo "- **平台:** `${{ matrix.platform.label }}`" >> $GITHUB_STEP_SUMMARY
          echo "- **版本:** `${VERSION}`" >> $GITHUB_STEP_SUMMARY
  

  build_linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            label: linux-x86_64
          - runner: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
            label: linux-aarch64

    steps:
      - name: 检出仓库
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 设置 rust
        uses: puniyu/setup-rust@a6d1a3adea77d13cf52ef1c0d9c02dc11f620e5a # main
        with:
          target: aarch64-linux-android x86_64-linux-android armv7-linux-androideabi i686-linux-android
          save-cache: true
          prefix-key: ${{ env.APP_NAME }}
          tools: tauri-cli

      - name: Setup Nodejs
        uses: puniyu/setup-node@bc6a83c5c09bd93e10596d6a9938fcfe5841f434 # main
        with:
          node-version: lts/*
          pnpm-version: 10.25.0
          cache: true


      - name: 配置 webkit
        uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # latest
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: 配置arm64
        if: ${{ matrix.platform.label == 'linux-aarch64' }}
        uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # latest
        with:
          packages: gcc-aarch64-linux-gnu libwebkit2gtk-4.1-dev:arm64

      - name: 构建
        run: |
          pnpm install
          cargo tauri build --target ${{ matrix.platform.target }}
        working-directory: piccy_app

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-app-${{ matrix.platform.label }}"
          path: |
            target/${{ matrix.platform.target }}/release/bundle/deb/${{ env.APP_NAME }}*.deb

      - name: 生成构建信息
        run: |
          VERSION=$(jq -r '.version' piccy_app/tauri.conf.json)
          NAME=$(jq -r '.productName' piccy_app/tauri.conf.json)
          
          echo "## Linux应用构建完成" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 应用信息" >> $GITHUB_STEP_SUMMARY
          echo "- **应用名称:** \`$NAME\`" >> $GITHUB_STEP_SUMMARY
          echo "- **平台:** \`${{ matrix.platform.label }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **版本:** \`$VERSION\`" >> $GITHUB_STEP_SUMMARY

  build_android:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: aarch64-linux-android
            label: android-aarch64

    steps:
      - name: 检出仓库
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 设置 rust
        uses: puniyu/setup-rust@a6d1a3adea77d13cf52ef1c0d9c02dc11f620e5a # main
        with:
          target: ${{ matrix.platform.target }}
          save-cache: true
          prefix-key: ${{ env.APP_NAME }}
          tools: tauri-cli

      - name: Setup Nodejs
        uses: puniyu/setup-node@bc6a83c5c09bd93e10596d6a9938fcfe5841f434 # main
        with:
          node-version: lts/*
          pnpm-version: 10.25.0
          cache: true

      - name: 配置 webkit
        uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # latest
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: 配置ndk
        id: setup-ndk
        uses: nttld/setup-ndk@ed92fe6cadad69be94a966a7ee3271275e62f779 # v1.6.0
        with:
          ndk-version: r27d

      - name: 设置 Android 签名
        run: |
          echo "storeFile=keystore.jks" > keystore.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          echo "${{ secrets.BASE64_JKS }}" | base64 --decode > app/keystore.jks

        working-directory: piccy_app/gen/android


      - name: 构建
        run: |
          pnpm install
          cargo tauri android build
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        working-directory: piccy_app

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-app-${{ matrix.platform.label }}"
          path: |
            piccy_app/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk

      - name: 生成构建信息
        run: |
          VERSION=$(jq -r '.version' piccy_app/tauri.conf.json)
          NAME=$(jq -r '.productName' piccy_app/tauri.conf.json)
          
          echo "## Android应用构建完成" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 应用信息" >> $GITHUB_STEP_SUMMARY
          echo "- **应用名称:** \`$NAME\`" >> $GITHUB_STEP_SUMMARY
          echo "- **平台:** \`${{ matrix.platform.label }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **版本:** \`$VERSION\`" >> $GITHUB_STEP_SUMMARY

